Added Docker build & push

diff --git a/api-gateway/makefile b/api-gateway/makefile
--- a/api-gateway/makefile
+++ b/api-gateway/makefile
@@ -15,11 +15,19 @@ rm:
 	@ docker stop ${CONTAINER_NAME}
 	@ docker rm ${CONTAINER_NAME}
 
+# docker-login:
+# 	@ echo "Logging in to Docker..."
+# 	@ echo ${DOCKER_TOKEN} | docker login -u ${DOCKER_USERNAME} --password-stdin ${DOCKER_REGISTRY}
+# 	@ echo "Login successful!"
 docker-login:
 	@ echo "Logging in to Docker..."
 	@ echo ${DOCKER_TOKEN} | docker login -u ${DOCKER_USERNAME} --password-stdin ${DOCKER_REGISTRY}
+	@ if [ $$? -ne 0 ]; then \
+        echo "Docker login failed"; \
+        exit 1; \
+    fi
 	@ echo "Login successful!"
-
+	
 push: build
 	@ if [ -z "${DOCKER_REGISTRY}" ]; then \
 	    echo "DOCKER_REGISTRY is not set. Using default (docker.io)"; \
@@ -36,3 +44,4 @@ push: build
 print-vars:
 	@ echo "DOCKER_REGISTRY=${DOCKER_REGISTRY}"
 	@ echo "DOCKER_USERNAME=${DOCKER_USERNAME}"
+
